Fix x509 proxy on cmslpc condor

diff --git a/csub b/csub
--- a/csub
+++ b/csub
@@ -11,19 +11,14 @@ timestamp = str(time.time()).replace(".","_")
 #sys.path.insert(0, os.path.expandvars("$CMSSW_BASE/src/MyTools/RootUtils/scripts"))
 #from csub_tar import make_tarball, get_tarball_path
 
-def get_os_container(required_os):
-    print(f"/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/{required_os}:x86_64")
+def get_os_container(required_os, hostname):
+    if "cmslpc" in hostname:
+        # Use rhel containers, as x509 proxy doesn't work with unpacked.cern.ch el* containers
+        container = f"/cvmfs/singularity.opensciencegrid.org/cmssw/cms:rh{required_os}-x86_64"
+    else:
+        container = f"/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/rh{required_os}:x86_64"
 
-    container = f"/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/{required_os}:x86_64"
-
-    #if os.path.isdir(f"/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/{required_os}:amd64"):
-    #    container = f"/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/{required_os}:amd64"
-    #elif os.path.isdir(f"/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/{required_os}:x86_64"):
-    #    container = f"/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/{required_os}:x86_64"
-    #else:
-    #    raise ValueError(f"I couldn't find a container for OS {required_os}. Please check /cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/{required_os}*.")
     return container
-
 
 parser = argparse.ArgumentParser(description = 'qsub-like interface to condor')
 parser.add_argument('script', type=str, help='Script to execute.')
@@ -39,7 +34,8 @@ parser.add_argument('-n', '--queue_n', type=int, default=1, help="Queue n jobs f
 parser.add_argument('-o', '--transfer_output', type=str, help="Specify specific output files to transfer back")
 parser.add_argument('-t', '--time_limit', type=str, default="longlunch", help="JobFlavour option (espresso=20min, microcentury=1hr, longlunch=2hr, workday=8hr, tomorrow=1day, testmatch=3day, nextweek=1week")
 parser.add_argument('-p', '--pythonpath', action='store_true', help="Use the current PYTHONPATH")
-parser.add_argument('-O', '--os', type=str, default="el8", choices=["el7", "el8", "el9"], help="Specify OS")
+parser.add_argument('-O', '--os', type=str, default=None, choices=["el7", "el8", "el9"], help="Specify OS (condor submission method)")
+parser.add_argument('--internal_os', type=str, default=None, choices=["el7", "el8", "el9"], help="Specify OS (directly run singularity inside job)")
 parser.add_argument('-j', '--nThreads', type=int, default=1, help="Request multiple cores")
 parser.add_argument('--no_submit', action='store_true', help="Prepare jobs but don't submit")
 #parser.add_argument('--cmssw', action='store_true', help='Transfer CMSSW libraries as a tarball')
@@ -48,17 +44,23 @@ parser.add_argument('--no_retar', action='store_true', help='Use existing tarbal
 parser.add_argument("--x509", "-x", type=str, default=None, help="Path to x509 proxy")
 args = parser.parse_args()
 
+import socket
+hostname = socket.gethostname()
+
+if args.os and args.internal_os:
+    raise ValueError("Cannot specify --os and --internal_os")
+
+# Make list of files to transfer to worker node
+files_to_transfer = []
+script_fullpath = os.path.abspath(args.script)
+files_to_transfer.append(script_fullpath)
 
 starting_directory = os.getcwd()
 if args.working_directory:
     os.system("mkdir -pv " + args.working_directory)
     os.chdir(args.working_directory)
 
-# Make list of files to transfer to worker node
-files_to_transfer = []
-files_to_transfer.append(args.script)
-
-cmssw_version = os.path.expandvars("$CMSSW_VERSION")
+#cmssw_version = os.path.expandvars("$CMSSW_VERSION")
 
 #data_directory = "/uscms/home/dryu/nobackup/"
 #data_directory = "/home/dryu/data/"
@@ -99,6 +101,7 @@ if args.pythonpath:
 
 # Make top-level script
 top_script_name = "condor_run_" + timestamp + ".sh"
+files_to_transfer.append(os.path.abspath(top_script_name))
 top_script = open(top_script_name, 'w')
 top_script.write(f"""#!/bin/bash
 source /cvmfs/cms.cern.ch/cmsset_default.sh
@@ -132,15 +135,33 @@ for env_name, env_value in env_to_transfer.items():
 
 #top_script.write("scripts=(" + " ".join([os.path.basename(x) for x in scripts]).rstrip() + ")\n")
 if args.x509:
-    x509_fullpath = os.path.expandvars(args.x509)
+    x509_fullpath = os.path.abspath(os.path.expandvars(args.x509))
     top_script.write("export X509_USER_PROXY=$(readlink -e $_CONDOR_SCRATCH_DIR/{})\n".format(os.path.basename(x509_fullpath)))
     top_script.write("echo $X509_USER_PROXY\n")
     top_script.write("ls -lrth $X509_USER_PROXY\n")
     top_script.write("voms-proxy-info -all\n")
     files_to_transfer.append(x509_fullpath)
 
+
+if args.internal_os:
+    # This is how MCM setups up containers inside jobs. Condor's built-in support is preferable.
+    top_script.write(f"""
+if [ -e \"/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/{args.internal_os}:amd64\" ]; then
+  CONTAINER_NAME=\"{args.internal_os}:amd64\"
+elif [ -e \"/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/{args.internal_os}:x86_64\" ]; then
+  CONTAINER_NAME=\"{args.internal_os}:x86_64\"
+else
+  echo \"Could not find amd64 or x86_64 for {args.internal_os}\"
+  exit 1
+fi
+export SINGULARITY_CACHEDIR=\"/tmp/$(whoami)/singularity\"
+singularity run  -B $(readlink -f /cvmfs) -B $(readlink -f /etc/grid-security) -B $(readlink -f /etc/pki/ca-trust) -B $(readlink -f /etc/grid-security/certificates) /cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/$CONTAINER_NAME {os.path.basename(args.script)} $1
+    """)
+
+else:
+    top_script.write(f"source {os.path.basename(args.script)} $1")
+
 top_script.write(f"""
-source {os.path.basename(args.script)} $1
 echo \"Job done.\"
 
 echo \"Contents of current directory:\"
@@ -153,7 +174,16 @@ runtime=$((end-start))
 echo \"Run time $runtime\"
 """)
 top_script.close()
-files_to_transfer.append(top_script_name)
+
+# Validate input files
+bad_files = []
+for input_file in files_to_transfer:
+    if not os.path.exists(input_file):
+        bad_files.append(input_file)
+if len(bad_files) >= 1:
+    print(bad_files)
+    raise ValueError("Some input files don't exist")
+
 
 # Make submission script
 if args.submit_file:
@@ -176,9 +206,6 @@ when_to_transfer_output = on_exit
 
 if args.os:
     ''' This is the old way before containers, where you could request nodes with a specific OS
-    # Try to get hostname
-    import socket
-    hostname = socket.gethostname()
     if "cmslpc" in hostname:
         if args.os == "SLCern6" or args.os == "sl6":
             submission_file.write("+DesiredOS=\"SL6\"\n")
@@ -187,17 +214,19 @@ if args.os:
     else:
         submission_file.write("requirements = (OpSysAndVer =?= \"{}\")\n".format(args.os))
     '''
-    import socket
-    hostname = socket.gethostname()
     if "cmslpc" in hostname:
-        submission_file.write(f"+ApptainerImage = \"{get_os_container(args.os)}\"\n")
+        submission_file.write(f"+ApptainerImage = \"{get_os_container(args.os, hostname)}\"\n")
     else:      
-        submission_file.write(f"MY.SingularityImage = \"{get_os_container(args.os)}\"\n")
+        submission_file.write(f"MY.SingularityImage = \"{get_os_container(args.os, hostname)}\"\n")
+
 if args.nThreads:
     submission_file.write("request_cpus = {}\n".format(args.nThreads))
+
 submission_file.write("+JobFlavour = \"{}\"\n".format(args.time_limit))
+
 if args.transfer_output:
     submission_file.write("transfer_output_files = " + args.transfer_output + "\n")
+
 if args.log:
     log_stdout = args.log + ".$(Cluster).$(Process).stdout"
     log_stderr = args.log + ".$(Cluster).$(Process).stderr"
@@ -206,6 +235,7 @@ else:
     log_stdout = "log_" + timestamp + "_$(Cluster).$(Process).stdout"
     log_stderr = "log_" + timestamp + "_$(Cluster).$(Process).stderr"
     log_condor = "log_" + timestamp + "_$(Cluster).$(Process).condor"
+
 submission_file.write(f"""
 output = {log_stdout}
 error = {log_stderr}
